spring:
  profiles:
    active: dev
  application:
    name: file-system

server:
  port: 9004

minio:
  endpoint: http://127.0.0.1:9090
  port: 9000
  accessKey: minioadmin
  secretKey: minioadmin
  secure: false
  bucketName: my-test
  fileSize: 1073741824
