spring:
  profiles:
    active: dev
  application:
    name: file-system

server:
  port: 9004

minio:
  endpoint: http://youngmanltj.xyz
  port: 9000
  accessKey: minioAdmin
  secretKey: minioAdmin
  secure: false
  bucketName: my-bucket
  fileSize: 1073741824
