server:
    port:
        9003
eureka:
    client:
        service-url:
            defaultzone:
                http://localhost:8761/eureka/
spring:
    application:
        name:
            server
    datasource:
        url:
            jdbc:mysql://localhost:3306/exam_system?characterEncoding=UTF8&autoReconnect=true
        username:
            root
        password:
            12345678
    driver-class-name:
        com.mysql.jdbc.Driver
    redis:
        host:
            localhost
        port:
            6379
        password:
            123456
    data:
        mongodb:
            authentication-database:
                admin
            host:
                localhost
            port:
                27017
            username:
                root
            password:
                123456
            database:
                resource
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest

mybatis-plus:
    mapper-locations:
        classpath*:
            mapper/*.xml

interfaceAccess:
    second: 10
    time: 5
    lockTime: 20
